[package]
name = "oh-regex-jsonrpc"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.3"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"

anyhow = "1.0.102"
html-escape = "0.2.13"

[profile.release]
lto = true          # Link Time Optimization
codegen-units = 1   # 减少生成单元，提高优化空间
opt-level = "z"     # "z" 最大体积优化（比 s 更激进），"s" 优化大小，默认 "3" 优化速度
panic = "abort"      # 去掉 unwind 相关代码
strip = true         # 自动去符号（新 Rust 支持
